test_that("prepare requires a checked plan", {
  root = .copy_test_fixture(
    "prepare",
    "regular"
  )

  expect_error(
    prepare(
      discover(
        validate(root)
      )
    ),
    "`plan` must be an object returned by check().",
    fixed = TRUE
  )
})

test_that("prepare generates regular indexes and book structure", {
  root = .copy_test_fixture(
    "prepare",
    "regular"
  )

  plan = prepare(
    check(
      discover(
        validate(root)
      )
    )
  )

  expect_true(plan$prepared)
  expect_true(plan$changed)

  project = plan$projects[[1L]]
  publication = project$publication

  expect_s3_class(
    publication,
    "iasi_quarto_publication"
  )

  expect_identical(
    publication$chapters,
    c(
      "index.qmd",
      "chapters/01-intro/index.qmd",
      "chapters/02-basics/index.qmd"
    )
  )

  intro_index = file.path(
    root,
    "chapters",
    "01-intro",
    "index.qmd"
  )

  expect_identical(
    readLines(
      intro_index,
      warn = FALSE,
      encoding = "UTF-8"
    ),
    c(
      "<!-- Generated by iasi.quarto. Do not edit. -->",
      "",
      "# Intro",
      "",
      "{{< include 01-introduction.qmd >}}",
      "",
      "{{< include 02-what-is.qmd >}}"
    )
  )

  expect_identical(
    readLines(
      file.path(
        root,
        "_book-structure.yml"
      ),
      warn = FALSE,
      encoding = "UTF-8"
    ),
    c(
      "book:",
      "  chapters:",
      '    - "index.qmd"',
      '    - "chapters/01-intro/index.qmd"',
      '    - "chapters/02-basics/index.qmd"'
    )
  )
})

test_that("prepare updates an existing regular index", {
  root = .copy_test_fixture(
    "prepare",
    "regular-index"
  )

  index_path = file.path(
    root,
    "chapters",
    "01-intro",
    "index.qmd"
  )

  expect_identical(
    readLines(
      index_path,
      warn = FALSE
    ),
    "old content"
  )

  plan = prepare(
    check(
      discover(
        validate(root)
      )
    )
  )

  expect_true(plan$changed)

  expect_true(
    any(grepl(
      "Generated by iasi.quarto",
      readLines(
        index_path,
        warn = FALSE
      )
    ))
  )
})

test_that("prepare is stable when artifacts have not changed", {
  root = .copy_test_fixture(
    "prepare",
    "regular"
  )

  first = prepare(
    check(
      discover(
        validate(root)
      )
    )
  )

  second = prepare(first)

  expect_true(first$changed)
  expect_false(second$changed)
})

test_that("prepare preserves structured indexes and writes parts", {
  root = .copy_test_fixture(
    "prepare",
    "structured"
  )

  index_path = file.path(
    root,
    "chapters",
    "01-intro",
    "index.qmd"
  )

  original = readLines(
    index_path,
    warn = FALSE,
    encoding = "UTF-8"
  )

  plan = prepare(
    check(
      discover(
        validate(root)
      )
    )
  )

  expect_identical(
    readLines(
      index_path,
      warn = FALSE,
      encoding = "UTF-8"
    ),
    original
  )

  expect_identical(
    readLines(
      file.path(
        root,
        "_book-structure.yml"
      ),
      warn = FALSE,
      encoding = "UTF-8"
    ),
    c(
      "book:",
      "  chapters:",
      '    - "index.qmd"',
      '    - part: "chapters/01-intro/index.qmd"',
      "      chapters:",
      '        - "chapters/01-intro/01-what-is.qmd"',
      '    - part: "chapters/02-basics/index.qmd"',
      "      chapters:",
      '        - "chapters/02-basics/01-prerequisites.qmd"'
    )
  )

  expect_true(plan$valid)
})

test_that("prepare writes a flat direct structure", {
  root = .copy_test_fixture(
    "prepare",
    "direct"
  )

  plan = prepare(
    check(
      discover(
        validate(root)
      )
    )
  )

  expect_identical(
    plan$projects[[1L]]$publication$chapters,
    c(
      "index.qmd",
      "chapters/01-intro/01-first.qmd",
      "chapters/02-more/01-second.qmd"
    )
  )

  expect_false(
    file.exists(
      file.path(
        root,
        "chapters",
        "01-intro",
        "index.qmd"
      )
    )
  )
})

test_that("prepare rejects an invalid checked plan", {
  root = .copy_test_fixture(
    "prepare",
    "invalid"
  )

  plan = check(
    discover(
      validate(root)
    )
  )

  expect_false(plan$valid)

  expect_error(
    prepare(plan),
    "IASI Quarto check failed:",
    fixed = TRUE
  )
})
