.prepare_navbar_left = function(project) {
  .write_if_changed(
    .navbar_left_yaml(project),
    .navbar_left_path(project)
  )
}

.navbar_left_yaml = function(project) {
  items = .navbar_left_items(project)

  lines = c(
    "# Generated by iasi.quarto. Copy and edit as needed.",
    if (length(items)) "left:" else "left: []"
  )

  if (length(items)) {
    for (item in items) {
      lines = c(
        lines,
        .navbar_item_lines(item)
      )
    }
  }

  lines = c(
    lines,
    "# End generated by iasi.quarto."
  )

  paste0(
    "    ",
    lines
  )
}

.navbar_left_items = function(project) {
  items = list()

  root_index = file.path(
    project$path,
    "index.qmd"
  )

  if (.navbar_document_enabled(root_index)) {
    items = c(
      items,
      list(list(
        text = .navbar_document_label(root_index),
        href = "index.qmd"
      ))
    )
  }

  for (folder in project$folders) {
    item = .navbar_folder_item(
      folder = folder,
      project = project
    )

    if (!is.null(item)) {
      items = c(
        items,
        list(item)
      )
    }
  }

  items
}

.navbar_folder_item = function(folder, project) {
  index = file.path(
    folder$path,
    "index.qmd"
  )

  if (!file.exists(index) || !.navbar_document_enabled(index)) {
    return(NULL)
  }

  children = .navbar_folder_children(
    folder = folder,
    project = project
  )

  label = .navbar_document_label(index)

  if (!length(children)) {
    return(list(
      text = label,
      href = .relative_path(
        index,
        project$path
      )
    ))
  }

  list(
    text = label,
    menu = children
  )
}

.navbar_folder_children = function(folder, project) {
  children = list()
  index = file.path(
    folder$path,
    "index.qmd"
  )

  if (.navbar_document_enabled(index)) {
    children = c(
      children,
      list(list(
        text = "Introducción",
        href = .relative_path(
          index,
          project$path
        )
      ))
    )
  }

  if (!is.null(folder$intro) && .navbar_document_enabled(folder$intro)) {
    children = c(
      children,
      list(.navbar_document_item(
        folder$intro,
        project
      ))
    )
  }

  if (!is.null(folder$items) && length(folder$items)) {
    for (item in folder$items) {
      child = .navbar_folder_child_item(
        item = item,
        project = project
      )

      if (!is.null(child)) {
        children = c(
          children,
          list(child)
        )
      }
    }

    return(children)
  }

  if (!is.null(folder$documents) && length(folder$documents)) {
    for (document in folder$documents) {
      if (!.navbar_document_enabled(document)) {
        next
      }

      children = c(
        children,
        list(.navbar_document_item(
          document,
          project
        ))
      )
    }
  }

  children
}

.navbar_folder_child_item = function(item, project) {
  if (identical(item$kind, "document")) {
    if (!.navbar_document_enabled(item$path)) {
      return(NULL)
    }

    return(.navbar_document_item(
      item$path,
      project
    ))
  }

  if (identical(item$kind, "chapter")) {
    index = file.path(
      item$chapter$path,
      "index.qmd"
    )

    if (!file.exists(index) || !.navbar_document_enabled(index)) {
      return(NULL)
    }

    return(.navbar_document_item(
      index,
      project
    ))
  }

  NULL
}

.navbar_document_item = function(path, project) {
  list(
    text = .navbar_document_label(path),
    href = .relative_path(
      path,
      project$path
    )
  )
}

.navbar_document_enabled = function(path) {
  metadata = .qmd_front_matter(path)

  .navbar_valid_label(
    metadata[["navbar-title"]]
  )
}

.navbar_document_label = function(path) {
  metadata = .qmd_front_matter(path)
  metadata[["navbar-title"]]
}

.navbar_valid_label = function(value) {
  is.character(value) &&
    length(value) == 1L &&
    !is.na(value) &&
    nzchar(value)
}

.qmd_front_matter = function(path) {
  if (!file.exists(path)) {
    return(list())
  }

  lines = readLines(
    path,
    warn = FALSE,
    encoding = "UTF-8"
  )

  if (!length(lines) || trimws(lines[[1L]]) != "---") {
    return(list())
  }

  closing = which(
    trimws(lines[-1L]) %in% c(
      "---",
      "..."
    )
  )

  if (!length(closing)) {
    return(list())
  }

  end = closing[[1L]] + 1L

  if (end <= 2L) {
    return(list())
  }

  front = paste(
    lines[2L:(end - 1L)],
    collapse = "\n"
  )

  metadata = tryCatch(
    yaml::yaml.load(front),
    error = function(error) NULL
  )

  if (!is.list(metadata)) {
    return(list())
  }

  metadata
}

.navbar_item_lines = function(item) {
  text = .yaml_double_quote(item$text)

  if (!is.null(item$href)) {
    return(c(
      sprintf(
        "  - text: %s",
        text
      ),
      sprintf(
        "    href: %s",
        .yaml_double_quote(item$href)
      )
    ))
  }

  lines = c(
    sprintf(
      "  - text: %s",
      text
    ),
    "    menu:"
  )

  for (child in item$menu) {
    lines = c(
      lines,
      sprintf(
        "      - text: %s",
        .yaml_double_quote(child$text)
      ),
      sprintf(
        "        href: %s",
        .yaml_double_quote(child$href)
      )
    )
  }

  lines
}

.yaml_double_quote = function(value) {
  value = gsub(
    "\\\\",
    "\\\\\\\\",
    value
  )

  value = gsub(
    '"',
    '\\\\"',
    value,
    fixed = TRUE
  )

  sprintf(
    '"%s"',
    value
  )
}
