.generated_header = "<!-- Generated by iasi.quarto. Do not edit. -->"

.include_lines = function(files) {
  if (!length(files)) {
    return(character())
  }

  lines = unlist(
    lapply(
      files,
      function(file) {
        c(
          sprintf(
            "{{< include %s >}}",
            file
          ),
          ""
        )
      }
    ),
    use.names = FALSE
  )

  utils::head(
    lines,
    -1L
  )
}

.book_yaml = function(chapters) {
  c(
    "book:",
    "  chapters:",
    sprintf(
      '    - "%s"',
      chapters
    )
  )
}


.book_chapter_lines = function(paths, root) {
  documents = .relative_paths(
    paths,
    root
  )

  if (!length(documents)) {
    return(character())
  }

  sprintf(
    '    - "%s"',
    documents
  )
}

.relative_paths = function(paths, root) {
  if (!length(paths)) {
    return(character())
  }

  unname(vapply(
    paths,
    .relative_path,
    character(1),
    root = root
  ))
}
