.generated_header <- "<!-- Generated by iasi.quarto. Do not edit. -->"

.include_lines <- function(files) {
  if (!length(files)) {
    return(character())
  }

  lines <- unlist(
    lapply(
      files,
      function(file) {
        c(sprintf("{{< include %s >}}", file), "")
      }
    ),
    use.names = FALSE
  )

  utils::head(lines, -1L)
}

.write_includes_index <- function(target, documents) {
  content <- c(
    .generated_header,
    "",
    .include_lines(basename(documents))
  )

  .write_if_changed(content, target)
}

.numbered_root_documents <- function(project) {
  documents <- project$root_documents[
    grepl(
      "^[0-9]+-.*\\.qmd$",
      basename(project$root_documents),
      ignore.case = TRUE
    )
  ]

  .relative_path(sort(documents), project$path)
}

.book_yaml <- function(chapters) {
  c(
    "book:",
    "  chapters:",
    sprintf('    - "%s"', chapters)
  )
}
