.generated_header <- "<!-- Generated by iasi.quarto. Do not edit. -->"

.write_includes_index <- function(target, documents) {
  includes <- sprintf("{{< include %s >}}", basename(documents))
  content <- c(.generated_header, "")

  if (length(includes)) {
    content <- c(content, as.vector(rbind(includes, rep("", length(includes)))))
    content <- content[-length(content)]
  }

  .write_if_changed(content, target)
}
