.build_project <- function(project) {
  switch(
    project$type,
    structured = .build_structured(project),
    regular = .build_regular(project),
    paper = .build_paper(project),
    mixed = .build_mixed(project),
    stop(sprintf("Unsupported project type '%s'.", project$type), call. = FALSE)
  )
}

.build_structured <- function(project) {
  chapters <- list()

  for (folder in project$folders) {
    if (identical(folder$strategy, "as-is")) {
      chapters <- c(chapters, .as_is_entries(folder))
      next
    }

    documents <- folder$documents[
      tolower(basename(folder$documents)) != "index.qmd"
    ]

    chapters <- c(
      chapters,
      list(list(
        part = .relative_path(file.path(folder$path, "index.qmd"), project$path),
        chapters = .relative_path(documents, project$path)
      ))
    )
  }

  .write_book_structure(project, chapters)
}

.build_regular <- function(project) {
  chapters <- character()

  for (folder in project$folders) {
    if (identical(folder$strategy, "as-is")) {
      chapters <- c(chapters, .as_is_entries(folder))
      next
    }

    .write_regular_index(folder)
    chapters <- c(
      chapters,
      .relative_path(file.path(folder$path, "index.qmd"), project$path)
    )
  }

  .write_book_structure(project, chapters)
}

.build_paper <- function(project) {
  root_00 <- file.path(project$path, "00-index.qmd")
  root_index <- file.path(project$path, "index.qmd")

  if (file.exists(root_00)) {
    documents <- project$root_documents[
      !tolower(basename(project$root_documents)) %in% c("index.qmd", "00-index.qmd")
    ]
    .write_includes_index(
      target = root_index,
      documents = c(root_00, documents)
    )
  }

  documents <- sort(list.files(
    project$path,
    pattern = "\\.qmd$",
    full.names = TRUE,
    recursive = FALSE,
    ignore.case = TRUE
  ))
  documents <- documents[tolower(basename(documents)) != "00-index.qmd"]
  documents <- .relative_path(documents, project$path)

  # index.qmd is always the Quarto home page and must be first.
  documents <- c("index.qmd", setdiff(documents, "index.qmd"))
  .write_book_structure(project, documents)
}

.build_mixed <- function(project) {
  entries <- unlist(
    lapply(project$folders, .as_is_entries),
    recursive = FALSE,
    use.names = FALSE
  )
  .write_book_structure(project, entries)
}

.as_is_entries <- function(folder) {
  documents <- folder$documents[
    !tolower(basename(folder$documents)) %in% c("00-index.qmd")
  ]
  .relative_path(documents, dirname(dirname(folder$path)))
}

.write_regular_index <- function(folder) {
  documents <- folder$documents[
    !tolower(basename(folder$documents)) %in% c("index.qmd")
  ]

  # 00-index.qmd is infrastructure and must be the first include.
  first <- file.path(folder$path, "00-index.qmd")
  documents <- c(first, setdiff(documents, first))

  .write_includes_index(
    target = file.path(folder$path, "index.qmd"),
    documents = documents
  )
}

.write_includes_index <- function(target, documents) {
  includes <- sprintf("{{< include %s >}}", basename(documents))
  content <- c(
    "<!-- Generated by iasi.quarto. Do not edit. -->",
    "",
    as.vector(rbind(includes, rep("", length(includes))))
  )
  if (length(includes)) content <- content[-length(content)]
  .write_if_changed(content, target)
}

.write_book_structure <- function(project, chapters) {
  structure <- list(book = list(chapters = chapters))
  output <- file.path(project$path, "_book-structure.yml")
  yaml::write_yaml(structure, output)
  message(sprintf("Book structure written to %s.", output))
  invisible(output)
}

.write_if_changed <- function(content, path) {
  current <- if (file.exists(path)) {
    readLines(path, warn = FALSE, encoding = "UTF-8")
  } else {
    character()
  }

  if (identical(current, content)) return(invisible(FALSE))
  writeLines(content, path, useBytes = TRUE)
  invisible(TRUE)
}

.relative_path <- function(path, root) {
  if (!length(path)) return(character())

  root <- .slash(normalizePath(root, winslash = "/", mustWork = TRUE))
  path <- .slash(normalizePath(path, winslash = "/", mustWork = FALSE))
  prefix <- paste0(root, "/")

  vapply(
    path,
    function(item) {
      if (startsWith(item, prefix)) {
        substring(item, nchar(prefix) + 1L)
      } else {
        item
      }
    },
    character(1),
    USE.NAMES = FALSE
  )
}
