.discover_project <- function(path = ".") {
  project_path <- .normalise_project_path(path)
  quarto_file <- file.path(project_path, "_quarto.yml")

  if (!file.exists(quarto_file)) {
    stop(
      sprintf("No Quarto project found in '%s': missing _quarto.yml.", project_path),
      call. = FALSE
    )
  }

  chapters_path <- file.path(project_path, "chapters")
  folders <- if (dir.exists(chapters_path)) {
    .discover_numbered_folders(chapters_path)
  } else {
    list()
  }

  counts <- .count_strategies(folders)

  project <- list(
    path = project_path,
    quarto_file = .slash(quarto_file),
    chapters_path = .slash(chapters_path),
    type = .infer_project_type(counts, folders),
    folders = folders,
    counts = counts,
    root_documents = .discover_root_documents(project_path)
  )

  class(project) <- "iasi_quarto_project"
  project
}

.normalise_project_path <- function(path) {
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)
  sub("/$", "", path)
}

.discover_numbered_folders <- function(chapters_path) {
  directories <- list.dirs(
    path = chapters_path,
    recursive = FALSE,
    full.names = TRUE
  )

  directories <- directories[grepl("^[0-9]{2}-", basename(directories))]
  directories <- directories[!grepl("^00-", basename(directories))]
  directories <- sort(directories)

  lapply(directories, .discover_folder)
}

.discover_folder <- function(path) {
  documents <- sort(list.files(
    path = path,
    pattern = "\\.qmd$",
    full.names = TRUE,
    recursive = FALSE,
    ignore.case = TRUE
  ))

  has_marker <- file.exists(file.path(path, "index.txt"))
  index_path <- file.path(path, "index.qmd")
  has_index <- file.exists(index_path)
  has_00_index <- file.exists(file.path(path, "00-index.qmd"))
  generated_index <- has_index && .is_generated_index(index_path)

  strategy <- if (has_marker) {
    "as-is"
  } else if (has_index && has_00_index && !generated_index) {
    "incoherent"
  } else if (has_00_index) {
    "regular"
  } else if (has_index) {
    "structured"
  } else {
    "unclassified"
  }

  list(
    name = basename(path),
    path = .slash(path),
    strategy = strategy,
    marker = has_marker,
    has_index = has_index,
    has_00_index = has_00_index,
    generated_index = generated_index,
    documents = .slash(documents)
  )
}

.count_strategies <- function(folders) {
  wanted <- c("structured", "regular", "as-is", "unclassified", "incoherent")
  counts <- setNames(integer(length(wanted)), wanted)

  if (length(folders)) {
    strategies <- vapply(folders, `[[`, character(1), "strategy")
    counts[] <- as.integer(table(factor(strategies, levels = wanted)))
  }

  as.list(counts)
}

.infer_project_type <- function(counts, folders) {
  if (counts$incoherent > 0L || counts$unclassified > 0L) {
    return("incoherent")
  }

  if (counts$structured > 0L && counts$regular > 0L) {
    return("incoherent")
  }

  if (counts$structured > 0L) return("structured")
  if (counts$regular > 0L) return("regular")
  if (!length(folders)) return("paper")

  "mixed"
}

.discover_root_documents <- function(project_path) {
  documents <- sort(list.files(
    path = project_path,
    pattern = "\\.qmd$",
    full.names = TRUE,
    recursive = FALSE,
    ignore.case = TRUE
  ))

  .slash(documents)
}

.is_generated_index <- function(path) {
  if (!file.exists(path)) return(FALSE)
  first <- readLines(path, n = 1L, warn = FALSE, encoding = "UTF-8")
  identical(first, "<!-- Generated by iasi.quarto. Do not edit. -->")
}

.slash <- function(path) {
  gsub("\\\\", "/", path)
}
